name: Ketan
favicon: null
layout_spectrum: 0.1976443415042013
typography_spectrum: 0.33332286309450865
title: 'Ketan '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6875482737086713
  lightness: 0.5420520778279752
  saturation: 0.1336426076013595
  rhythmicContrast: 0.6147695481777191
purpose: []
