name: Ketan
favicon: null
layout_spectrum: 0.1976443415042013
typography_spectrum: 0.33332286309450865
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ececec'
    - '#d9d9d7'
    - '#abadac'
    - '#cacbc6'
  brandStrength: 0.6875482737086713
  lightness: 0.5420520778279752
  saturation: 0.3125
  rhythmicContrast: 0.6147695481777191
purpose: []
